### ISSUE TITLE
Error "Could not convert database value 'of type object' to Doctrine Type datetime_immutable"

### ISSUE THREAD

**Issue by ThomasLandauer** [VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle#17]
I have Symfony 2.8.15 with Doctrine DBAL 2.5.5 and I'm getting this error:  
> Could not convert database value "of type object" to Doctrine Type datetime_immutable  

with a reference to vendor\doctrine\dbal\lib\Doctrine\DBAL\Types\ConversionException.php line 46

**Comment by VasekPurchart** [comment]
Hello, whis should mean, that you are storing an object in a `datetime_immutable` mapped field, but the object is not of `DateTimeInterface` type and therefore it cannot be processed.

Please make sure what object are you passing in the field? If you are not sure add `var_dump($value);die;` in `vendor/vasek-purchart/doctrine-date-time-immutable-types/src/DateTimeImmutableType.php` method `convertToDatabaseValue`.

If this object is instance of your own DateTime implementation or something like that, make sure it implements `DateTimeInterface`.

**Comment by ThomasLandauer** [comment]
Sorry, I forgot to mention: It did work before, but after a `composer update` today I'm getting this error on many pages.  

Your suggested `var_dump()` gives me: 
> object(AppBundle\Entity\DateTimeNow)#104 (0) {
}

**Comment by VasekPurchart** [comment]
Yes, this is because of the changes in https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types/commit/600f95109cd463f57bb5d72950463a0ffb3eced0 where forward compatibility with Doctrine DBAL 2.6.x is implemented , which also added stricter checks (so "regular" DateTimes will fail in a similar way with new DBAL version, when it is released)

The key to solution of you problem is described in my previous comment, please follow the instructions there.

**Comment by ThomasLandauer** [comment]
Here's how I created the `DateTimeNow`: http://stackoverflow.com/questions/31947364/doctrine-set-current-timestamp-as-default-value-by-the-database-i-e-not-by-ph/37924640#37924640

**Comment by VasekPurchart** [comment]
Yes, that is exactly what I am writing, you are trying to store an object, which does not implement `DateTimeInterface`(http://php.net/manual/en/class.datetimeinterface.php) and therefore cannot be worked with safely. This won't also work when you update Doctrine to the newer version, as I mentioned.

Either you have to implement the interface, or use `DateTime`/`DateTimeImmutable`.

---

By the way, what you are trying to achieve there goes straight against Doctrine's usecase, because the object you are storing is completely different from what you are getting. So in fact your entities are not safe to be used in code until they are loaded back from the database, so in fact the object is inconsistent until then. Also when you are using Doctrine ORM it is expected, that you business logic resides in the application, not in the database, so creating times should be in fact responsibility of the application, not the database and ideally every manipulation of the database should go trough the application, so the times would be consistent. Anyway this is now really off topic, just wanted to warn you, that what you are doing will bring you probably more problems along the way.

**Comment by ThomasLandauer** [comment]
Thanks! You're certainly right that this is not the best way to do it ;-)  

Since we already started this somewhat offtopic discussion:  
I was looking for an easy way to do it like in the old days: Having a timestamp column in the database, set to CURRENT_TIMESTAMP, and then just omitting this column from the INSERT statement. But it looks like there is no easy way to achieve this in Doctrine, huh?  
What would you recommend? What's the best practice? Do this in the entity?:
````php
    public function doPrePersist()
    {
        $this->timestamp = new \DateTime();
    }
