### ISSUE TITLE
Error `Unknown column type "datetime_immutable" requested`

### ISSUE THREAD

**Issue by ThomasLandauer** [VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle#23]
When doing `doctrine:schema:update --force` on an empty PostgreSQL database, it works. But when I do it again, I'm getting:
> [Doctrine\DBAL\DBALException]
  Unknown column type "datetime_immutable" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use  AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

On SQLite, it always works.  
I also tried it without your bundle, but I get the same error.

Environment:
* PHP 7.0
* Symfony 3.3
* doctrine/dbal 2.5.13
* vasek-purchart/doctrine-date-time-immutable-types-bundle 1.0
* config.yml:
```yml
doctrine_date_time_immutable_types:
    register: replace
```

Thanks for any help! :-)

**Comment by VasekPurchart** [comment]
Hello, I have not encountered this myself, but a friend of mine, told me about same/similar behavior he encountered, while updating doctrine. I think this is either an issue caused by doctrine/orm or doctrine/dbal. I guess you were updating something from that? I think you have two options:

1) Update all the related packages (orm, dbal, doctrine bundle) to the latest versions, which also means, that they already include "native" DT immutable types, in your case, you should keep this bundle, in version [2.0](https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle/releases/tag/2.0), because you were using the replace option - this is exactly what I did.
2) See what you upgraded, downgrade it again (where it should be working) and then try to figure out what went wrong :)

Btw what might be related is https://github.com/doctrine/DoctrineBundle/issues/673, because it tries to make a connection to the database very early in the process, try looking into that (you will probably need it anyway :) .

**Comment by ThomasLandauer** [comment]
Yeah, Doctrine was upgraded when I upgraded to Symfony 3.3. To be able to upgrade to Doctrine DBAL 1.6 (which has native support for immutable), I need to upgrade to PHP 7.1 first: https://github.com/doctrine/dbal/releases/tag/v2.6.0

Thanks!

**Comment by VasekPurchart** [comment]
Np, glad you figured it out :)

**Comment by ThomasLandauer** [comment]
Uprading to PHP 7.1 (and consequently to doctrine/dbal 2.6.1) did indeed solve this issue.

However, after I changed all my column definitions from `datetime` to `datetime_immutable`, a new issue popped up: https://github.com/Atlantic18/DoctrineExtensions/issues/1820

I would say you should mention this use case (namely maintain compatibility with `timestampable`) in https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle/blob/master/readme.md near:
> this bundle no longer uses custom DateTime types implementation, but rather offers control,

**Comment by VasekPurchart** [comment]
>However, after I changed all my column definitions from datetime to datetime_immutable

Well there is absolutely no need to make this step, if you do not plan to use both `datetime` and `datetime_immutable`, so exactly what `replace` used to be for, it does the same - it will register the new DBAL types "over" the old ones as well, so you don't need to change anything, if you keep using this bundle (that's why I did not deprecate it and released the 2.0 version).

**Comment by ThomasLandauer** [comment]
Yeah, I know. But I wanted to uninstall the bundle, to simplify my dependencies. I'm still in development phase, so I can easily change stuff...
